AWSTemplateFormatVersion: 2010-09-09
Description: A sample CloudFormation template with YAML comments.
# Resources section
Resources:
  GitSyncVPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.1/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
        - Value: gitsyncvpc
  GitSyncSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitSyncVPC
      CidrBlock: 10.0.0.1/24
      Tags:
        - Key: Name
        - Value: Gitsync